### ISSUE TITLE
Support new decorators proposal

### ISSUE THREAD

**Issue by hedgepigdaniel** [leonardfactory/babel-plugin-transform-typescript-metadata#16]
Any chance of supporting the new decorators proposal - i.e. not requiring the `legacy` flag for `@babel/plugin-proposal-decorators`?

**Comment by leonardfactory** [comment]
The issue here is due to [reflect-metadata](https://github.com/rbuckton/reflect-metadata) package, which is the one used under the hood. 
This plugin just translates actual types into `reflect-metadata`-compatible decorations. I suppose, since latest decorator proposal is pretty different from original one, code will not work. Furthermore, all decorators I've found playing around (like nest, etc.) uses legacy format, which is the one outputted by TSC compiler by the way. Diverging from it seems to me like diverging from TSC behaviour, and this will definitely break anything made with TypeScript compiler in mind (so.. everything 😄). If you've got more insights I'd be glad to hear them.
